"""Add new profile fields

Revision ID: 5e65383ca1d9
Revises: e2a255a7eed6
Create Date: 2026-10-04 17:16:16.994158

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5e65383ca1d9'
down_revision: str | None = 'e2a255a7eed6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

