"""Add is_premium to user

Revision ID: 82f958a7818a
Revises: a59f38fd6cba
Create Date: 2026-10-02 21:08:03.551345

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '82f958a7818a'
down_revision: str | None = 'a59f38fd6cba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_premium')
    # ### end Alembic commands ###

