"""Add chat models

Revision ID: d8717b8fd755
Revises: 82f958a7818a
Create Date: 2026-10-03 16:26:54.619205

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd8717b8fd755'
down_revision: str | None = '82f958a7818a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'candidato_id', name='uq_chat_empresa_candidato')
    )
    op.create_index(op.f('ix_chat_rooms_candidato_id'), 'chat_rooms', ['candidato_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_empresa_id'), 'chat_rooms', ['empresa_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chat_rooms_empresa_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_candidato_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###

