"""add extra profile fields

Revision ID: e2a255a7eed6
Revises: d8717b8fd755
Create Date: 2026-10-04 16:54:45.977914

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e2a255a7eed6'
down_revision: str | None = 'd8717b8fd755'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfiles_candidato', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('perfiles_candidato', sa.Column('portfolio_url', sa.String(length=255), nullable=True))
    op.add_column('perfiles_candidato', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('perfiles_candidato', sa.Column('job_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfiles_candidato', 'job_title')
    op.drop_column('perfiles_candidato', 'about_me')
    op.drop_column('perfiles_candidato', 'portfolio_url')
    op.drop_column('perfiles_candidato', 'phone')
    # ### end Alembic commands ###

