name: Fetch Backend Log

on:
  push:
    branches:
      - main

jobs:
  fetch-log:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Get Log
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'INNER_EOF'
            tail -n 100 ~/BACKEND_CODEX/backend/backend.log
            exit
          INNER_EOF
